apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n 
  labels:
    app.kubernetes.io/name: 'n8n'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: 'latest'
    app.kubernetes.io/part-of: 'n8n'
    component: configmap
data:
  NODE_ENV: "production"
  GENERIC_TIMEZONE: "America/Recife"
  WEBHOOK_TUNNEL_URL: "http://n8n.onobrerodrigo.tech/" 
  # Database configurations
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_HOST: "n8n-postgres.n8n.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: n8n-secrets
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'n8n'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: 'latest'
    app.kubernetes.io/part-of: 'n8n'
stringData:
  # Database password
  DB_POSTGRESDB_PASSWORD: "123qwe"
  # Basic auth credentials
  N8N_BASIC_AUTH_PASSWORD: "n8n"
  # Encryption key to hash all data
  N8N_ENCRYPTION_KEY: "n8n"
  N8N_SECURE_COOKIE: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: n8n-service
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'n8n'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: 'latest'
    app.kubernetes.io/part-of: 'n8n'
spec:
  selector:
    app.kubernetes.io/name: 'n8n'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: 'latest'
    app.kubernetes.io/part-of: 'n8n'
  ports:
  - name: n8n-http
    port: 80
    targetPort: 5678
    protocol: TCP
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'n8n'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: 'latest'
    app.kubernetes.io/part-of: 'n8n'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: 'n8n'
      app.kubernetes.io/env: 'dev'
      app.kubernetes.io/version: 'latest'
      app.kubernetes.io/part-of: 'n8n'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'n8n'
        app.kubernetes.io/env: 'dev'
        app.kubernetes.io/version: 'latest'
        app.kubernetes.io/part-of: 'n8n'
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: n8n-http
          containerPort: 5678
        envFrom:
        - configMapRef:
            name: n8n-configmap
        - secretRef:
            name: n8n-secrets
        resources:
          limits:
            cpu: "1.0"
            memory: "1024Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
