apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap-deployment
  namespace: n8n 
  labels:
    app.kubernetes.io/name: 'n8n'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: 'latest'
    app.kubernetes.io/part-of: 'n8n'
data:
  NODE_ENV: "production"
  GENERIC_TIMEZONE: "America/Recife"
  WEBHOOK_TUNNEL_URL: "https://n8n.ginga.dev.br/" 
  WEBHOOK_URL: "https://n8n.ginga.dev.br/" 
  # Database configurations
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_HOST: "n8n-service-postgres.n8n.svc.cluster.local"
  DB_POSTGRESDB_PORT: "5432"
