apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret-deployment
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'n8n'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: 'latest'
    app.kubernetes.io/part-of: 'n8n'
type: Opaque   
data:
  # Database password
  DB_POSTGRESDB_PASSWORD: "MTIzcXdl"
  # Basic auth credentials
  N8N_BASIC_AUTH_PASSWORD: "bjhu"
  # Encryption key to hash all data
  N8N_ENCRYPTION_KEY: "bjhu"
  N8N_SECURE_COOKIE: "ZmFsc2U="