apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-deployment
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'n8n'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: 'latest'
    app.kubernetes.io/part-of: 'n8n'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: 'n8n'
      app.kubernetes.io/env: 'dev'
      app.kubernetes.io/version: 'latest'
      app.kubernetes.io/part-of: 'n8n'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'n8n'
        app.kubernetes.io/env: 'dev'
        app.kubernetes.io/version: 'latest'
        app.kubernetes.io/part-of: 'n8n'
    spec:
      containers:
      - name: n8n
        image: n8nio/n8n:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: n8n-http
          containerPort: 5678
        envFrom:
        - configMapRef:
            name: n8n-configmap-deployment
        env:
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secret-deployment
              key: DB_POSTGRESDB_PASSWORD
        - name: N8N_BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: n8n-secret-deployment
              key: N8N_BASIC_AUTH_PASSWORD
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: n8n-secret-deployment
              key: N8N_ENCRYPTION_KEY
        - name: N8N_SECURE_COOKIE
          valueFrom:
            secretKeyRef:
              name: n8n-secret-deployment
              key: N8N_SECURE_COOKIE
        resources:
          limits:
            cpu: "1.0"
            memory: "1024Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
