apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret-postgres
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'postgres'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: '14.8'
    app.kubernetes.io/part-of: 'n8n'
type: Opaque
data:
  POSTGRES_DB: 'bjhu'
  POSTGRES_USER: 'bjhu'
  POSTGRES_PASSWORD: 'MTIzcXdl'