apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: n8n-infisical-postgres
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'postgres'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/part-of: 'n8n'
spec:
  hostAPI: https://app.infisical.com/api
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: n8n
      secretsScope:
        envSlug: dev
        secretsPath: "/postgres"
  managedSecretReference:
    secretName: n8n-infisical-postgres
    secretNamespace: n8n
    creationPolicy: "Orphan"