apiVersion: v1
kind: Service
metadata:
  name: n8n-postgres-service
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'postgres'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: '14.8'
    app.kubernetes.io/part-of: 'n8n'
spec:
  selector:
    app.kubernetes.io/name: 'postgres'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: '14.8'
    app.kubernetes.io/part-of: 'n8n'
  ports:
  - name: n8n-postgres
    protocol: TCP
    port: 5432
    targetPort: 5432