# IMPORTANTE: a maioria das variáveis ​​de ambiente usadas pelo aplicativo vêm de
# um serviço externo Infisical (https://app.infisical.com)

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n-statefulset-postgres
  namespace: n8n
  labels:
    app.kubernetes.io/name: 'postgres'
    app.kubernetes.io/env: 'dev'
    app.kubernetes.io/version: '14.8'
    app.kubernetes.io/part-of: 'n8n'
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 'postgres'
      app.kubernetes.io/env: 'dev'
      app.kubernetes.io/version: '14.8'
      app.kubernetes.io/part-of: 'n8n'
  serviceName: n8n-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'postgres'
        app.kubernetes.io/env: 'dev'
        app.kubernetes.io/version: '14.8'
        app.kubernetes.io/part-of: 'n8n'
    spec:
      containers:
      - name: n8n-postgres
        image: postgres:14
        imagePullPolicy: IfNotPresent
        ports:
        - name: postgres-port
          containerPort: 5432
          protocol: TCP
        envFrom:
        - secretRef:
            name: n8n-infisical-postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      storageClassName: standard
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
